name: CI

on:
  pull_request:
  push:
    branches: [develop]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency: ci

jobs:
  test:
    name: Validate on ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: true
          - name: macOS (Intel)
            os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - name: macOS (Apple Silicon)
            os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true
          submodules: recursive

      - name: Install Rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        id: rust_cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        id: check_fmt
        run: |
          cargo fmt --check

      - name: Clippy
        id: clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        id: test
        run: |
          cargo test --all-features
